<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bank_model extends CI_Model
{

    public $table = 'bank';
    public $id = 'id_rekening';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_rekening,nama_bank,atas_nama,nomor');
        $this->datatables->from('bank');
        //add this line for join
        //$this->datatables->join('table2', 'bank.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/bank/read/$1'),'Read')." | ".anchor(site_url('admin/bank/update/$1'),'Update')." | ".anchor(site_url('admin/bank/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_rekening');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_rekening', $q);
	$this->db->or_like('nama_bank', $q);
	$this->db->or_like('atas_nama', $q);
	$this->db->or_like('nomor', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_rekening', $q);
	$this->db->or_like('nama_bank', $q);
	$this->db->or_like('atas_nama', $q);
	$this->db->or_like('nomor', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Bank_model.php */
/* Location: ./application/models/Bank_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-26 02:03:53 */
/* http://harviacode.com */