<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kas_model extends CI_Model
{

    public $table = 'kas';
    public $id = 'idp';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($i) {
        $this->datatables->select('idp,tanggal,keterangan,jenis,saldo');
        $this->datatables->from('kas');
        if ($i==date("Y-m-d")) {
            $this->datatables->where('DATE(tanggal) = DATE(NOW())');
        }else{
            $this->datatables->where('DATE(`tanggal`) = "'.$i.'"');
        }
        //add this line for join
        //$this->datatables->join('table2', 'kas.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('kas/read/$1'),'Read')." | ".anchor(site_url('kas/update/$1'),'Update')." | ".anchor(site_url('kas/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'idp');
        return $this->datatables->generate();
    }

    // get all
    function get_all($i)
    {
        $this->db->order_by($this->id, $this->order);
        if ($i==date("Y-m-d")) {
            $this->db->where('DATE(tanggal) = DATE(NOW())');
        }else{
            $this->db->where('DATE(`tanggal`) = "'.$i.'"');
        }
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idp', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('saldo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idp', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('jenis', $q);
	$this->db->or_like('saldo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kas_model.php */
/* Location: ./application/models/Kas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-16 03:14:21 */
/* http://harviacode.com */