<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Listmenu_model extends CI_Model
{

    public $table = 'listmenu';
    public $id = 'id_menu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('listmenu.id_menu,nama_menu,harga,listmenu.id_kategori,deskripsi_menu,foto_menu,status,kategori.id_kategori as idk,kategori.nama_kategori');
        $this->datatables->from('listmenu');
        //add this line for join
        //$this->datatables->join('table2', 'listmenu.field = table2.field');
        $this->datatables->join('kategori', 'listmenu.id_kategori = kategori.id_kategori');
        $this->datatables->add_column('action', anchor(site_url('admin/listmenu/read/$1'),'Read')." | ".anchor(site_url('admin/listmenu/update/$1'),'Update')." | ".anchor(site_url('admin/listmenu/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_menu');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_menu', $q);
	$this->db->or_like('nama_menu', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('deskripsi_menu', $q);
	$this->db->or_like('foto_menu', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_menu', $q);
	$this->db->or_like('nama_menu', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('deskripsi_menu', $q);
	$this->db->or_like('foto_menu', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Listmenu_model.php */
/* Location: ./application/models/Listmenu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-04-12 05:21:17 */
/* http://harviacode.com */