<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Order_model extends CI_Model
{

    public $table = 'order';
    public $id = 'id_order';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_order,id_user,metode,diskon,bayar,total_harga,date,waktu,transaksi,id_kasir,nama_kasir');
        $this->datatables->from('order');
        $this->datatables->where('status', 'lunas');
        //add this line for join
        //$this->datatables->join('table2', 'order.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('order/read/$1'),'Read'), 'id_order');
        return $this->datatables->generate();
    }    
    function json2() {
        $this->datatables->select('order.id_order,id_user,total_harga,waktu,transaksi,id_kasir,nama_kasir,users.first_name');
        $this->datatables->from('order');
        $this->datatables->where('status', 'belum bayar');
        //add this line for join
        $this->datatables->join('users', 'order.id_user = users.id');
        $this->datatables->add_column('action', anchor(site_url('admin/pesanantamu/ckt/$1'),'Check Out')." | ".anchor(site_url('admin/pesanantamu/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_order');
        return $this->datatables->generate();
    }

    // get all
    function get_all($i)
    {
        $this->db->order_by($this->id, $this->order);
        if ($i==date("Y-m-d")) {
            $this->db->where('DATE(date) = DATE(NOW())');
        }else{
            $this->db->where('DATE(`date`) = "'.$i.'"');
        }
        return $this->db->get($this->table)->result();
    }

    function get_all_where_id($id)
    {
        $this->db->order_by($this->id, "DESC");
        $this->db->where("id_user", $id);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_order', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('total_harga', $q);
	$this->db->or_like('waktu', $q);
	$this->db->or_like('transaksi', $q);
	$this->db->or_like('id_kasir', $q);
	$this->db->or_like('nama_kasir', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_order', $q);
	$this->db->or_like('id_user', $q);
	$this->db->or_like('total_harga', $q);
	$this->db->or_like('waktu', $q);
	$this->db->or_like('transaksi', $q);
	$this->db->or_like('id_kasir', $q);
	$this->db->or_like('nama_kasir', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($table,$id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($table);
    }

}

/* End of file Order_model.php */
/* Location: ./application/models/Order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-04-17 08:36:58 */
/* http://harviacode.com */