<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Page_model extends CI_Model
{

    public $table = 'page';
    public $link = 'link';
    public $id = 'id_page';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_page,link,judul,deskripsi,foto,enum');
        $this->datatables->from('page');
        //add this line for join
        //$this->datatables->join('table2', 'page.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('admin/page/read/$1'),'Read')." | ".anchor(site_url('admin/page/update/$1'),'Update')." | ".anchor(site_url('admin/page/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_page');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    // get data by id
    function get_by_link($link)
    {
        $this->db->where($this->link, $link);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_page', $q);
	$this->db->or_like('link', $q);
	$this->db->or_like('judul', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('enum', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_page', $q);
	$this->db->or_like('link', $q);
	$this->db->or_like('judul', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('foto', $q);
	$this->db->or_like('enum', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Page_model.php */
/* Location: ./application/models/Page_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-19 06:28:20 */
/* http://harviacode.com */