<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Bank extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Bank_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $data = array('title' => 'bank');
        $this->template->load('template','admin/bank/bank_list', $data);
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Bank_model->json();
    }

    public function read($id) 
    {
        $row = $this->Bank_model->get_by_id($id);
        if ($row) {
            $data = array(
                'title' => 'Read',
		'id_rekening' => $row->id_rekening,
		'nama_bank' => $row->nama_bank,
		'atas_nama' => $row->atas_nama,
		'nomor' => $row->nomor,
	    );
            $this->template->load('template','admin/bank/bank_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/bank'));
        }
    }

    public function create() 
    {
        $data = array(
            'title' => 'Create',
            'button' => 'Create',
            'action' => site_url('admin/bank/create_action'),
	    'id_rekening' => set_value('id_rekening'),
	    'nama_bank' => set_value('nama_bank'),
	    'atas_nama' => set_value('atas_nama'),
	    'nomor' => set_value('nomor'),
	);
        $this->template->load('template','admin/bank/bank_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_bank' => $this->input->post('nama_bank',TRUE),
		'atas_nama' => $this->input->post('atas_nama',TRUE),
		'nomor' => $this->input->post('nomor',TRUE),
	    );

            $this->Bank_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('admin/bank'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Bank_model->get_by_id($id);

        if ($row) {
            $data = array(
                'title' => 'Update',
                'button' => 'Update',
                'action' => site_url('admin/bank/update_action'),
		'id_rekening' => set_value('id_rekening', $row->id_rekening),
		'nama_bank' => set_value('nama_bank', $row->nama_bank),
		'atas_nama' => set_value('atas_nama', $row->atas_nama),
		'nomor' => set_value('nomor', $row->nomor),
	    );
            $this->template->load('template','admin/bank/bank_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/bank'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_rekening', TRUE));
        } else {
            $data = array(
		'nama_bank' => $this->input->post('nama_bank',TRUE),
		'atas_nama' => $this->input->post('atas_nama',TRUE),
		'nomor' => $this->input->post('nomor',TRUE),
	    );

            $this->Bank_model->update($this->input->post('id_rekening', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('admin/bank'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Bank_model->get_by_id($id);

        if ($row) {
            $this->Bank_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('admin/bank'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/bank'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_bank', 'nama bank', 'trim|required');
	$this->form_validation->set_rules('atas_nama', 'atas nama', 'trim|required');
	$this->form_validation->set_rules('nomor', 'nomor', 'trim|required');

	$this->form_validation->set_rules('id_rekening', 'id_rekening', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Bank.php */
/* Location: ./application/controllers/Bank.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-06-26 02:03:53 */
/* http://harviacode.com */