<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kas extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Kas_model');
        $this->load->model('Order_model');
        $this->load->model('Web_model');
        $this->load->library('form_validation');        
	    $this->load->library('datatables');
    }

    public function index($dated='')
    {
        $dated = ($dated) ? $dated : date("Y-m-d");
        $das = $this->Order_model->get_all($dated);
        $data = array(
            'title' => 'Laporan Transaksi',
            'date'=>$dated,
            'dats'=>$das,
        );
        $this->template->load('template','admin/kas/kas_list', $data);
    } 
    
    public function json($i) {
        header('Content-Type: application/json');
        echo $this->Kas_model->json($i);
    }

    public function read($id) 
    {
        $this->load->model('Web_model');
        $row = $this->Order_model->get_by_id($id);
        $order_detail = $this->Web_model->get_all_where('order_detail','id_order', $id);
        if ($row) {
            $data = array(
                'title' => "No Nota ".$row->id_order,
                'id_order' => $row->id_order,
                'id_user' => $row->id_user,
                'total_harga' => $row->total_harga,
                'waktu' => $row->waktu,
                'date' => $row->date,
                'transaksi' => $row->transaksi,
                'id_kasir' => $row->id_kasir,
                'nama_kasir' => $row->nama_kasir,
                'metode' => $row->metode,
                'diskon' => $row->diskon,
                'bayar' => $row->bayar,
                'detail' => $order_detail->result(),
            );
            $this->template->load('template','admin/order/order_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('admin/kas'));
        }
    }

    public function update($id,$status) 
    {
        $data = array(
            'transaksi' => $status,
        );

        $this->Order_model->update($id, $data);
        $datas = array('id_order' => $id, 'status' => $status);
        $this->Web_model->insertall("notifikasi",$datas);
        redirect(site_url('admin/kas'));
    }
}

/* End of file Kas.php */
/* Location: ./application/controllers/Kas.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-16 03:14:21 */
/* http://harviacode.com */